### PR TITLE
Extend generated code

### PR DESCRIPTION
**Pull request by Shatur**
@pepijndevos thank you for providing this crate, it's a good place to start working with LiteX.
This PR contains the following changes:
1. Implement `core::fmt::Write` for UART. With this change it's possible to use UART like this:
```rust
writeln!(uart, "Hello, {}", "world");
```
2. Add constructors and destructors as [recommended](https://doc.rust-lang.org/beta/embedded-book/design-patterns/hal/interoperability.html?highlight=free#wrapper-types-provide-a-destructor-method-c-free) by the Embedded book.
3. Add `Debug` derive to be able to use `unwrap()` and `expect()` on `Option<Device>`.
4. Add `From` impl.

### CODE REVIEW

**Comment by pepijndevos** [comment]
Thanks!

**Comment by Shatur** [comment]
@pepijndevos could you publish your create on creates.io? I found it very useful to getting started with LiteX and Rust.

**Comment by pepijndevos** [comment]
uhh I guess? I have never done such a thing. Do I just type `cargo publish` or something.

**Comment by Shatur** [comment]
@pepijndevos [here](https://doc.rust-lang.org/cargo/reference/publishing.html) is the guide. Should be easy.

**Comment by Shatur** [comment]
@pepijndevos and I would suggest to rename the repo into just `litex-hal` to match the crate name.

**Pull request merged**
