### PR TITLE
Use dual license

### PR DESCRIPTION
**Pull request by Shatur**
It's just a suggestion, so if you disagree - feel free to close this PR.
I suggesting to use dual license to make this crate more accessible. This is what most crates do, like https://github.com/bevyengine/bevy

### CODE REVIEW

**Comment by pepijndevos** [comment]
Sigh I honestly don't really care but I'm fine with it. If we do it, we should do it well. IMO that means https://reuse.software/ compliance, making sure every file has a license header and all that. While still making sure Github can identify the license as well, which means picking one as the "primary" license to put in `LICENSE` and all the REUSE licenses in a LICENSES folder.

**Comment by Shatur** [comment]
> making sure every file has a license header and all that. 

I'm not a layer, but it looks like for MIT / Apache it isn't needed. At least all the crates I've seen was without license header in source files. Do you know a popular crate that does it?

> While still making sure Github can identify the license as well, which means picking one as the "primary" license to put in LICENSE and all the REUSE licenses in a LICENSES folder.

GitHub recently [received support of dual licensing](https://github.blog/changelog/2022-05-26-easily-discover-and-navigate-to-multiple-licenses-in-repositories/) and I just used the suggested names. This is also what other crates do. Should I move licenses into LICENSE folder instead?

**Comment by Shatur** [comment]
I've done a little research on other crates, and they all seem to use the `-MIT` and `-APACHE` or `.MIT` and `.APACHE` suffixes for license files in the root folder, and don't put license headers in the source files:
https://github.com/bevyengine/bevy
https://github.com/gfx-rs/wgpu
https://github.com/SergioBenitez/Rocket
https://github.com/serde-rs/serde
https://github.com/seanmonstar/reqwest
https://github.com/rustsec/rustsec/tree/main/cargo-audit
https://github.com/EmbarkStudios/cargo-deny

So we probably doing it right :)

**Comment by pepijndevos** [comment]
It is not a license requirement, it is simply good practice to add a SPDX identifier, so that if people copy paste random files around, license information is maintained. REUSE has a nice tool for adding them and verifying that all your files have the right info and your license files match the license of your files.

REUSE was recommended to my by some FSF lawyer people, so that's like... the pinnacle of whatever it is FSF is trying to accomplish.

The Github dual license option is indeed very recent, and very unfortunate that they chose a scheme that's incompatible with REUSE. You'd have to copy all the licenses around to comply with both. Ugh.

Well as I said I don't really care, so use your best judgement.

**Comment by Shatur** [comment]
> It is not a license requirement, it is simply good practice to add a SPDX identifier, so that if people copy paste random files around, license information is maintained. REUSE has a nice tool for adding them and verifying that all your files have the right info and your license files match the license of your files.

I agree with you, I also follow this practice for my GPL projects because [it clearly described](https://www.gnu.org/licenses/gpl-howto.html) in the official GPL page.
I just assumed that since the other popular "Apache or MIT" Rust projects don't do this (see the previous message), that's fine.
I could add SPDX identifiers, but could you help me to automate it? I don't have enough experience with it.

> The Github dual license option is indeed very recent, and very unfortunate that they chose a scheme that's incompatible with REUSE. You'd have to copy all the licenses around to comply with both. Ugh.

Yes, this sucks. GitHub in a nutshell :smile: 

> Well as I said I don't really care, so use your best judgement.

I would do the same as other projects. Their version looks easier to maintain :smile:
But if you want, we can try to automate the validation of SPDX and put the license files as recommended by REUSE by making symlinks.

**Pull request merged**
