### PR TITLE
Bump version to 0.2

### PR DESCRIPTION
**Pull request by Shatur**
May I ask you to draft a new release with the latest changes?
I bumped the minor version since it's technically a breaking change: we made `gpio` optional and switched to dual-license.

### CODE REVIEW

**Comment by pepijndevos** [comment]
Sure. Can I add you as contributor to the cargo package somehow? Or can we set up CI to automatically push git tags?

**Comment by Shatur** [comment]
> Sure. Can I add you as contributor to the cargo package somehow?

It looks like we can: https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner

**Comment by pepijndevos** [comment]
```
$ cargo owner --add Shatur
    Updating crates.io index
error: failed to invite owners to crate `litex-hal` on registry at https://crates.io

Caused by:
  the remote server responded with an error: could not find user with login `Shatur`
```

**Comment by Shatur** [comment]
@pepijndevos I should probably login first :D
Could you try it again?

**Comment by pepijndevos** [comment]
Done

**Pull request merged**
